# Generated by Django 6.1 on 2026-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('description', models.TextField()),
                ('apply_email', models.EmailField(help_text='Where applications for this role should be sent.', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this posting from the careers page without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
