# Generated by Django 6.1 on 2026-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('project_type', models.CharField(choices=[('new_app', 'New app build'), ('existing', 'Existing product / ongoing work'), ('mvp', 'MVP / prototype'), ('consulting', 'Technical consulting'), ('other', 'Something else')], default='new_app', max_length=20)),
                ('budget', models.CharField(choices=[('under_5k', 'Under $5k'), ('5_15k', '$5k - $15k'), ('15_50k', '$15k - $50k'), ('over_50k', '$50k+'), ('not_sure', 'Not sure yet')], default='not_sure', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
